name: run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Update tools
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 tar zstd
      - uses: actions/checkout@main
      - name: Download .tgz file
        run: aria2c -x 16 -s 128 --file-allocation=none -i download.txt
      - name: List structure of downloaded .tgz file
        run: tar -tzf download.tgz
      - name: Decompress .tgz file
        run: tar -xzf download.tgz
      - name: Delete files over 100MB and list their sizes
        run: |
          find . -type f -size +100M -exec ls -lh {} \; -delete
      - name: Recompress using zstd at level 22
        run: |
          tar --use-compress-program="zstd -22" -cf download.tar.zst -- *
      - name: Upload compressed file as artifact
        uses: actions/upload-artifact@main
        with:
          name: compressed-file
          path: download.tar.zst
          
