name: run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Update tools
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2
      - uses: actions/checkout@main
      - name: Download file
        run: aria2c -x 32 -s 32 --file-allocation=none -i download.txt
      - name: Rel
        uses: softprops/action-gh-release@master
        with:
          files: win.iso
          tag_name: "test"
         
