name: run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Update tools
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2  
      - uses: actions/checkout@main
      - name: Download file
        run: aria2c -x 16 -s 16 --file-allocation=none -i download.txt
      - name: Unzip files
        run: tar -xzf rom.tgz --wildcards '*/vendor_boot.img'
      - name: Upload file using actions/upload-artifact
        uses: actions/upload-artifact@main
        with:
          name: vendor_boot_img
          path: ./vendor_boot.img
