name: run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Update tools
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 tar zstd
      - uses: actions/checkout@main
      - name: Download .tgz file
        run: aria2c -x 16 -s 256 --file-allocation=none -i download.txt
      - name: Decompress .tgz file
        run: tar -xzf download.tgz
      - name: Delete .tgz archive
        run: rm download.tgz
      - name: List sizes of decompressed files in MB
        run: |
          find . -type f -exec ls -l {} \; | awk '{printf "%-50s %7.2f MB\n", $9, $5/1024/1024}'
      - name: Recompress using zstd at level 22
        run: |
          tar --use-compress-program="zstd -v -T0 --ultra -22" -cf download.tar.zst -- *
      - name: Upload compressed file as artifact
        uses: actions/upload-artifact@main
        with:
          name: compressed-file
          path: download.tar.zst
