name: run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Update tools
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 tar unzip
      - uses: actions/checkout@main
      - name: Download archive file
        run: aria2c -x 16 -s 16 --file-allocation=none -i download.txt
      - name: Decompress archive file
        run: |
          if [ -f download.tgz ]; then
            tar -xzf download.tgz
          elif [ -f download.zip ]; then
            unzip download.zip
          else
            echo "Error: Downloaded file is not .tgz or .zip"
            exit 1
          fi
      - name: Delete archive file
        run: |
          if [ -f download.tgz ]; then
            rm download.tgz
          elif [ -f download.zip ]; then
            rm download.zip
          fi
      - name: List sizes of decompressed files in MB
        run: |
          find . -type f -exec ls -l {} \; | awk '{printf "%-50s %7.2f MB\n", $9, $5/1024/1024}'
      - name: Find .bin file
        id: find_bin
        run: |
          bin_file=$(find . -type f -name "*.bin" | head -n 1)
          if [[ -n $bin_file ]]; then
            echo "::set-output name=bin_file::$bin_file"
            echo "Found .bin file: $bin_file"
          else
            echo "No .bin file found."
            exit 1
          fi
      - name: Upload .bin file as artifact
        if: success()
        uses: actions/upload-artifact@main
        with:
          name: run
          path: ${{ steps.find_bin.outputs.bin_file }}
          
